name: Publish as Yomitan Dictionary

on:
  push:
    branches:
      - main
      
permissions:
  contents: write  # Allows writing to the repository (creating releases)
  actions: read    # Allows reading the workflow run information

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Dictionary
      run: npm run build-and-run

    - name: Create Release
      id: create_release
      uses: thomaseizinger/create-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: R${{ github.run_number }}
        release_name: Yomitan Hololive Names Dictionary Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Yomitan Dictionary
      uses: softprops/action-gh-release@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/hololive-dictionary.zip
        asset_name: hololive-dictionary.zip
        asset_content_type: application/zip
