name: Publish as Yomitan Dictionary

on:
  push:
    branches:
      - main
      
permissions:
  contents: write  # Allows writing to the repository (creating releases)
  actions: read    # Allows reading the workflow run information

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Dictionary
      run: npm run build-and-run


    - name: Upload Yomitan Dictionary
      uses: softprops/action-gh-release@v2
      with:
        name: Yomitan Hololive Names Dictionary Release ${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./build/hololive-dictionary.zip
        tag_name: R${{ github.run_number }}
        draft: false
        prerelease: false
        
