name: Publish as Yomitan Library

on:
  push:
    branches:
      - main
      
permissions:
  contents: write  # Allows writing to the repository (creating releases)
  actions: read    # Allows reading the workflow run information

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Library
      run: npm run build-and-run

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: R${{ github.run_number }}
        release_name: Yomitan Library Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Yomitan Library
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/hololive-dictionary.tsv
        asset_name: hololive-dictionary.tsv
        asset_content_type: zip/application
